### ISSUE TITLE
pull_request.number is undefined

### ISSUE THREAD

**Issue by snebjorn** [nefrob/pr-description#1]
There seems to be an issue with getting the PR number when force-pushing.

My action trigger is:
```yml
on:
    pull_request:
        types: [labeled]
```

When I force-push to a PR with a label on it. I get this error:

```
/home/runner/work/_actions/nefrob/pr-description/v1.0.0/dist/index.js:9014
  const prNumber = github.context.payload.pull_request.number;
                                                       ^

TypeError: Cannot read properties of undefined (reading 'number')
    at run (/home/runner/work/_actions/nefrob/pr-description/v1.0.0/dist/index.js:9014:56)
```

**Comment by nefrob** [comment]
@snebjorn I haven't been able to repeat this since force pushing with the above action trigger does not run the action for me. Do you have auto labeling happening on PRs? Also if you could link to the code causing this (if the repo is public) that would be helpful.

It seems like missing pull request event data means the action was not triggered by a pull request webhook and perhaps we should just ignore running the action with a useful warning in that case?

Otherwise my prospective fix right now is to switch to using `github.context.issue` in case the pull request event data is not present, i.e. https://github.com/nefrob/pr-description/blob/631efb16beddadf707235592143fe25b22c24b7d/index.js#L12

This assumes `payload.number` is the pull request number re

https://github.com/actions/toolkit/blob/7b617c260dff86f8d044d5ab0425444b29fa0d18/packages/github/src/context.ts#L55-L62

which I need to double check. It seems there is some prior art here I could leverage or pull the necessary code from as well if needed, ex. https://github.com/jwalton/gh-find-current-pr.

**Comment by snebjorn** [comment]
I'll look into reproducing the exact conditions and get back to you

**Comment by snebjorn** [comment]
Sorry I got the trigger wrong. It was buried deep :)

The culprit is 
```yml
on:
  push:
    paths:
      - "mypath"
```
and labels and force-pushing is irrelevant.

Here's my test PR https://github.com/snebjorn/debug-pr-description/pull/1
With the failed run triggered by a push:
https://github.com/snebjorn/debug-pr-description/actions/runs/5948010153/job/16131003885?pr=1

**Comment by nefrob** [comment]
Ah yup that makes more sense, the `push` event will not have pull request info so it needs to be fetched from somewhere else. I can't view the above links but I think this should be enough to go off of here.

For now I'm going to update the readme to mention only `pull_request` events are supported and label this issue as a feature request. I'll take a look today if I have time.

**Comment by nefrob** [comment]
@snebjorn please retry against my fix branch `uses: nefrob/pr-description@nefrob/push-events-handling` (#3). If that works for you I will merge it and release today.

**Comment by snebjorn** [comment]
It works! 🚀

**Comment by nefrob** [comment]
Thanks! Released here: https://github.com/nefrob/pr-description/releases/tag/v1.1.0.
